<a href="https://colab.research.google.com/github/Punith6738/158CS21016CIE-33/blob/main/ASSIGNMENT_%E2%80%93_WEEK_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Logistics Regression function and SVM function.

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pandas as pd

In [ ]:
df = pd.read_csv("/content/train[1].csv")

In [ ]:
X = df[["Pclass"]]
y = df["Name"]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.2,random_state=23)

In [ ]:
Lg=LogisticRegression(random_state=0)

In [ ]:
Lg.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
pred_y=Lg.predict(X_test)

In [ ]:
Ac=accuracy_score(y_test,pred_y)
print("accuracy",Ac)

accuracy 0.0


In [ ]:
cnf=confusion_matrix(y_test,pred_y)
print("confusion matrix",cnf)

confusion matrix [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
cr=classification_report(y_test,pred_y)
print("classification Report",cr)

classification Report                                                                                     precision    recall  f1-score   support

                                                               Abbing, Mr. Anthony       0.00      0.00      0.00       1.0
                                                       Abbott, Mr. Rossmore Edward       0.00      0.00      0.00       1.0
                                                               Abelson, Mr. Samuel       0.00      0.00      0.00       1.0
                                             Abelson, Mrs. Samuel (Hannah Wizosky)       0.00      0.00      0.00       1.0
                                                    Adahl, Mr. Mauritz Nils Martin       0.00      0.00      0.00       1.0
                                                                   Adams, Mr. John       0.00      0.00      0.00       1.0
                                                        Aks, Mrs. Sam (Leah Rosen)       0.00      0.00      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

SVM function.

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/train[1].csv")

In [ ]:
X = df[["Pclass"]]
y = df["Name"]

In [ ]:
X,y = load_breast_cancer(return_X_y=True)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.2,random_state=23)

In [ ]:
Lg=SVC(random_state=0)

In [ ]:
Lg.fit(X_train,y_train)

SVC(random_state=0)

In [ ]:
pred_y=Lg.predict(X_test)

In [ ]:
Ac=accuracy_score(y_test,pred_y)
print("accuracy",Ac)

accuracy 0.8903508771929824


In [ ]:
cnf=confusion_matrix(y_test,pred_y)
print("confusion matrix",cnf)

confusion matrix [[122  47]
 [  3 284]]


In [ ]:
cr=classification_report(y_test,pred_y)
print("classification Report",cr)

classification Report               precision    recall  f1-score   support

           0       0.98      0.72      0.83       169
           1       0.86      0.99      0.92       287

    accuracy                           0.89       456
   macro avg       0.92      0.86      0.87       456
weighted avg       0.90      0.89      0.89       456



Basic Ensemble techniques

In [ ]:
#max voting
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

classifier1 = DecisionTreeClassifier(random_state=42)
classifier2 = SVC(probability=True, random_state=42)
classifier3 = LogisticRegression(random_state=42)

voting_classifier = VotingClassifier(estimators=[('dt', classifier1), ('svc', classifier2), ('lr', classifier3)], voting='hard')

voting_classifier.fit(X_train, y_train)

y_pred = voting_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
#averaging
import numpy as np

model1_predictions = np.array([0.1, 0.2, 0.3, 0.4])
model2_predictions = np.array([0.65, 0.75, 0.58, 0.88])
model3_predictions = np.array([0.72, 0.82, 0.62, 0.91])

ensemble_predictions = (model1_predictions + model2_predictions + model3_predictions) / 3

print("Ensemble Predictions:", ensemble_predictions)

Ensemble Predictions: [0.49 0.59 0.5  0.73]


In [ ]:

#weighted average
import numpy as np

base_model1_predictions = np.array([0.1, 0.2, 0.3, 0.4])
base_model2_predictions = np.array([0.6, 0.7, 0.8, 0.75])
base_model3_predictions = np.array([0.75, 0.65, 0.7, 0.8])

weights = [0.4, 0.3, 0.3]

ensemble_predictions = (
    weights[0] * base_model1_predictions +
    weights[1] * base_model2_predictions +
    weights[2] * base_model3_predictions
)

normalized_ensemble_predictions = ensemble_predictions / sum(weights)

print("Ensemble Predictions (Unnormalized):", ensemble_predictions)
print("Ensemble Predictions (Normalized):", normalized_ensemble_predictions)

Ensemble Predictions (Unnormalized): [0.445 0.485 0.57  0.625]
Ensemble Predictions (Normalized): [0.445 0.485 0.57  0.625]


Advance Ensemble

In [ ]:
#stacking
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

data = load_iris()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model1 = RandomForestClassifier(n_estimators=100, random_state=42)
model2 = GradientBoostingClassifier(n_estimators=100, random_state=42)

meta_model = LogisticRegression()

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)

pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)

meta_features = np.column_stack((pred1, pred2))

meta_model.fit(meta_features, y_test)

pred1_full = model1.predict(X)
pred2_full = model2.predict(X)

meta_features_full = np.column_stack((pred1_full, pred2_full))

final_predictions = meta_model.predict(meta_features_full)

accuracy = accuracy_score(y, final_predictions)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [ ]:
#boosting
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X, y = make_classification(n_samples=1000, n_features=20, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

base_classifier = DecisionTreeClassifier(max_depth=1)

adaboost = AdaBoostClassifier(base_classifier, n_estimators=50, random_state=42)

adaboost.fit(X_train, y_train)

y_pred = adaboost.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.87


In [ ]:
#bagging
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000,n_features=20,n_informative=15,random_state=5)
print(X.shape,y.shape)
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.ensemble import BaggingClassifier
X,y=make_classification(n_samples=1000,n_features=20,n_informative=15,random_state=5)
model=BaggingClassifier()
cv=RepeatedKFold(n_splits=10,n_repeats=3,random_state=1)
n_scores=cross_val_score(model,X,y,scoring='accuracy',cv=cv,n_jobs=-1, error_score='raise')
print('Accuracy:%.3f(%.3f)'%(mean(n_scores),std(n_scores)))

(1000, 20) (1000,)
Accuracy:0.855(0.032)
