<a href="https://colab.research.google.com/github/Punith6738/158CS21016CIE-33/blob/main/CIE_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LogisticRegression

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [ ]:
X,y = load_iris(return_X_y=True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
lg=LogisticRegression()

In [ ]:
lg.fit(X_train, y_train)

LogisticRegression()

In [ ]:
pred_y=lg.predict(X_test)

In [ ]:
AC=accuracy_score(y_test, pred_y)

In [ ]:
print("AC in %", AC*100)

AC in % 100.0


In [ ]:
cm=confusion_matrix(y_test, pred_y)

In [ ]:
print("confusion_matrix", cm)

confusion_matrix [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [ ]:
cr=classification_report(y_test, pred_y)

In [ ]:
print("classification_report", cr)

classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

df = pd.read_csv("/content/test[1].csv")

features = df[['x', 'y']]

k = 3

kmeans = KMeans(n_clusters=k)
kmeans.fit(features)

df['Cluster'] = kmeans.labels_

plt.scatter(features['x'], features['y'], c=kmeans.labels_, cmap='rainbow')
plt.xlabel('x')
plt.ylabel('y')
plt.title('K-Means Clustering')
plt.show()

SVM


In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.datasets import load_iris

In [ ]:
X,y = load_iris(return_X_y=True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
sv=SVC()

In [ ]:
sv.fit(X_train, y_train)

SVC()

In [ ]:
pred_y = sv.predict(X_test)

In [ ]:
AC=accuracy_score(y_test, pred_y)

In [ ]:
print("AC in %", AC*100)

AC in % 100.0


In [ ]:
cm = confusion_matrix(y_test, pred_y)

In [ ]:
print("confusion_matrix", cm)

confusion_matrix [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [ ]:
cr = classification_report(y_test, pred_y)

In [ ]:
print("classification_report", cr)

classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [ ]:
k_means

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/Social_Network_Ads[1].csv")

In [ ]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
k = 3

In [ ]:
kmeans = KMeans(n_clusters=k)
kmeans.fit(features)

NameError: ignored

PCA

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

In [ ]:
data = load_iris()

In [ ]:
X = data.data
y = data.target

In [ ]:
from numpy.random.mtrand import standard_normal
mean = np.mean(X,axis = 0)
std = np.std(X,axis = 0)
X_standradized=(X - mean) / std

In [ ]:
n_componets = 4

In [ ]:
pca = PCA("componets=n_componets")

In [ ]:
X_reduced = pca.fit_transform(X_standradized)

InvalidParameterError: ignored

In [ ]:
evr = pca.explained_variance_ratio_
print("Explained Variance Ratios:", evr)

AttributeError: ignored